### ISSUE TITLE
pythontex

### ISSUE THREAD

**Issue by TheChymera** [aponteeduardo/cpp_lecture#1]
Hi, I found your presentation very informative - and I think it is great you shared your sample code here on github!

If you would like to integrate "live" figures and code directly into your presentation and you are accustomed to LaTeX I would recommend looking into the `PythonTeX` and `minted` packages. I have used them to great satisfaction in the past, e.g in an [example document for a tutorial](https://bitbucket.org/TheChymera/ld_expert-doc/src) or a presentation about [free and open source scientific software](https://bitbucket.org/TheChymera/ld_expert).

**Comment by aponteeduardo** [comment]
Thank you @TheChymera, I have been looking for a package to combine Latex and python for a while. I will upload the slides and have a look at the package you're mentionihg :-)
